name: fazztrack_batch1
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.11.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: ^4.6.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/Rectangle 25.png
    - images/bell.jpg
    - images/1.png
    - images/1-1.png
    - images/netflix.png
    - images/spotify.png
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf

